"""add reason field to picnic

Revision ID: 0541d7feea26
Revises: ac555fee5aa6
Create Date: 2023-04-18 10:21:54.927999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0541d7feea26'
down_revision = 'ac555fee5aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picnic', sa.Column('reason', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picnic', 'reason')
    # ### end Alembic commands ###
